#!/usr/bin/env python3
"""
Setup script for Car Tuning AI Agent environment configuration.
"""

import os
import getpass
from pathlib import Path

def setup_environment():
    """Set up the environment configuration."""
    print("🚗 Car Tuning AI Agent Environment Setup")
    print("=" * 50)
    
    # Check if .env file already exists
    env_file = Path('.env')
    if env_file.exists():
        print("⚠️  .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/N): ").lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    print("\n📋 Setting up your environment variables...")
    print("\n🔑 Google API Key Setup:")
    print("1. Go to https://makersuite.google.com/app/apikey")
    print("2. Create a new API key")
    print("3. Copy the API key")
    
    # Get API key from user
    api_key = getpass.getpass("Enter your Google API key (input will be hidden): ").strip()
    
    if not api_key:
        print("❌ No API key provided. Setup cancelled.")
        return
    
    # Validate API key format (basic check)
    if not api_key.startswith('AI'):
        print("⚠️  Warning: Google API keys usually start with 'AI'. Please verify your key.")
        continue_setup = input("Continue anyway? (y/N): ").lower()
        if continue_setup != 'y':
            print("Setup cancelled.")
            return
    
    # Create .env file content
    env_content = f"""# Car Tuning AI Agent Environment Variables
# Generated by setup script

# Google API Key for Gemini 2.5 Flash
GOOGLE_API_KEY={api_key}

# Optional: Flask configuration
FLASK_ENV=development
FLASK_DEBUG=true
"""
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("\n✅ Environment file created successfully!")
        print("📁 File: .env")
        print("🔒 The file contains your API key - keep it secure!")
        
        # Add .env to .gitignore if not already there
        gitignore_file = Path('.gitignore')
        if not gitignore_file.exists():
            with open('.gitignore', 'w') as f:
                f.write("# Environment variables\n.env\n")
            print("📝 Added .env to .gitignore for security")
        else:
            with open('.gitignore', 'r') as f:
                content = f.read()
            if '.env' not in content:
                with open('.gitignore', 'a') as f:
                    f.write("\n# Environment variables\n.env\n")
                print("📝 Added .env to .gitignore for security")
        
        print("\n🎉 Setup complete! You can now run the application with LLM enhancement.")
        print("\nTo start the web interface:")
        print("  python3 web_app.py")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {str(e)}")

def check_environment():
    """Check if environment is properly configured."""
    print("🔍 Checking environment configuration...")
    
    # Load environment variables
    from dotenv import load_dotenv
    load_dotenv()
    
    api_key = os.getenv('GOOGLE_API_KEY')
    
    if api_key:
        print("✅ Google API key found in environment")
        print(f"🔑 Key: {api_key[:10]}...{api_key[-4:]}")
        return True
    else:
        print("❌ No Google API key found")
        print("💡 Run 'python3 setup_env.py' to configure your environment")
        return False

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1 and sys.argv[1] == 'check':
        check_environment()
    else:
        setup_environment() 